### ISSUE TITLE
Instruction for using SNOMED as training data

### ISSUE THREAD

**Issue by ashishkishor** [clips/fewshot-biomedical-names#3]
Can you please provide instruction how to train the model with SNOMED training data and how to do continual learning i.e. how to train from SNOMED-CD to ICD-10 and vice versa.
and how to use pretrained name representation that got from BioBERT model and BNE Model as it is mentioned in the paper and in repository by only using fast text ,training has been done.

**Comment by ashishkishor** [comment]
Could you please give some instruction how to run the model using SNOMED as training set

**Comment by PieterFivez** [comment]
Hello Ashish,

Since I'm not allowed to share SNOMED-CT data directly with anyone, I'll have to provide a script for automatically extracting the data from source files that you should provide. I'll look into it.
